# Generated by Django 4.2.11 on 2026-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('UPLOADER', 'Serial Uploader'), ('FULFILLER', 'Problem Solver'), ('POPULAR', 'Crowd Favorite'), ('GUARDIAN', 'Platform Guardian')], max_length=20)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'achievements',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.achievement'),
        ),
    ]
