# Generated by Django 4.2.11 on 2026-04-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_achievement_alter_user_options_user_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
