# Generated by Django 4.2.11 on 2026-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_remove_user_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shadow_banned',
            field=models.BooleanField(default=False),
        ),
    ]
