# Generated by Django 4.2.11 on 2026-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_member_id_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approval', 'Resource Approved'), ('rejection', 'Resource Rejected'), ('fulfillment', 'Request Fulfilled'), ('follow', 'New Follower'), ('mention', 'New Mention'), ('system', 'System Message')], max_length=20),
        ),
    ]
