# Generated by Django 4.2.11 on 2026-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_collection_resourcerequest_discussionthread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('literature', 'Literature'), ('history', 'History'), ('computer_science', 'Computer Science'), ('arts', 'Arts'), ('language', 'Language'), ('philosophy', 'Philosophy'), ('books', 'Books'), ('notes', 'Notes'), ('videos', 'Videos'), ('papers', 'Research Papers'), ('slides', 'Slides / Presentations'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
    ]
