# Generated by Django 4.2.11 on 2026-04-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='linked_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='resources.resourcerequest'),
        ),
    ]
