# Generated by Django 4.2.11 on 2026-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_linked_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='min_reputation',
            field=models.PositiveIntegerField(default=0, help_text='Minimum reputation points required to download this resource.'),
        ),
    ]
