# Generated by Django 4.2.11 on 2026-04-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_min_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='min_reputation',
        ),
    ]
