# Generated by Django 4.2.11 on 2026-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_remove_resource_min_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accuracy',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='clarity',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='completeness',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
